services:
  postgres:
    image: postgres:16-alpine
    container_name: cas_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # 2. The Java Backend
  java-backend:
    build:
      context: .
      dockerfile: cas-injector/Dockerfile
    container_name: cas_java_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cas_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - ./logs:/app/logs
      - ./cas-scraper:/app/cas-scraper
    depends_on:
      - postgres

  # 3. The Python Parser
  python-parser:
    build: ./cas-parser
    container_name: cas_python_app
    ports:
      - "8000:8000"
    environment:
      - JAVA_BACKEND_URL=http://java-backend:8080/api/cas/inject
    depends_on:
      - java-backend

  # 4. The React Frontend
  react-frontend:
    build: ./portfolio-dashboard
    container_name: cas_react_ui
    ports:
      - "80:80"
    depends_on:
      - java-backend
    restart: always

volumes:
  postgres_data:
