spring.application.name=portfolio-tracker

# 🛰️ Docker-Specific DB Connection
# Changed 'localhost' to 'db' (the service name in docker-compose)
spring.datasource.url=jdbc:postgresql://postgres:5432/cas_db
spring.datasource.username=user
spring.datasource.password=password

# 🛣️ Add a Context Path (Optional but recommended for Nginx cleanliness)
# This makes all your endpoints start with /api
server.servlet.context-path=/api
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# 📝 File Logging
logging.file.name=/app/logs/portfolio-os.log
# Keep logs for 30 days and max file size 10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.max-file-size=10MB